"""Exact ledgers for the renormalised scale-hull balance."""

from __future__ import annotations

from fractions import Fraction


Wavevector = tuple[int, int]
CosineLedger = dict[Wavevector, Fraction]


def similarity_drift_coefficient(q: Fraction) -> Fraction:
    """Return the coefficient of ``||V||_q^q`` in similarity time."""
    if q <= 1:
        raise ValueError("q must exceed one")
    return (q - 3) / (2 * q)


def gradient_packet_spacetime_power(p: Fraction) -> Fraction:
    """Return the radius power of ``int |grad u_R|^p dx dt``.

    A critical velocity packet has amplitude ``R^-1``, gradient amplitude
    ``R^-2``, spatial volume ``R^3``, and parabolic lifetime ``R^2``.
    """
    if p <= 0:
        raise ValueError("p must be positive")
    return Fraction(5) - 2 * p


def higher_integrability_packet_power(delta: Fraction) -> Fraction:
    """Specialise the packet power to ``p=2+delta``."""
    if delta < 0:
        raise ValueError("delta must be nonnegative")
    return gradient_packet_spacetime_power(Fraction(2) + delta)


def canonical_wavevector(wavevector: Wavevector) -> Wavevector:
    """Use ``cos(-k dot x)=cos(k dot x)`` to choose one representative."""
    first, second = wavevector
    if first < 0 or (first == 0 and second < 0):
        return (-first, -second)
    return wavevector


def add_mode(
    ledger: CosineLedger,
    wavevector: Wavevector,
    coefficient: Fraction,
) -> None:
    """Add one cosine mode and remove exact zero coefficients."""
    wavevector = canonical_wavevector(wavevector)
    ledger[wavevector] = ledger.get(wavevector, Fraction(0)) + coefficient
    if ledger[wavevector] == 0:
        del ledger[wavevector]


def cosine_product(
    left: Wavevector,
    right: Wavevector,
) -> CosineLedger:
    """Expand one product with ``2 cos(a)cos(b)=cos(a+b)+cos(a-b)``."""
    result: CosineLedger = {}
    add_mode(
        result,
        (left[0] + right[0], left[1] + right[1]),
        Fraction(1, 2),
    )
    add_mode(
        result,
        (left[0] - right[0], left[1] - right[1]),
        Fraction(1, 2),
    )
    return result


def pressure_poisson_rhs_modes() -> CosineLedger:
    """Return the exact modes of ``partial_i w_j partial_j w_i``.

    The divergence-free periodic field is generated by

    ``psi=-(cos(x)+cos(y)+cos(x+y))``,
    ``w=(partial_y psi,-partial_x psi,0)``.

    Writing ``a=cos(x)``, ``b=cos(y)``, and ``c=cos(x+y)``, direct
    differentiation gives the pressure Poisson source
    ``-2(ab+ac+bc)``.
    """
    a = (1, 0)
    b = (0, 1)
    c = (1, 1)
    result: CosineLedger = {}
    for left, right in ((a, b), (a, c), (b, c)):
        for wavevector, coefficient in cosine_product(left, right).items():
            add_mode(result, wavevector, -2 * coefficient)
    return result


def pressure_modes() -> CosineLedger:
    """Solve ``-Delta p=partial_i w_j partial_j w_i`` mode by mode."""
    result: CosineLedger = {}
    for wavevector, coefficient in pressure_poisson_rhs_modes().items():
        wave_number_squared = (
            wavevector[0] ** 2
            + wavevector[1] ** 2
        )
        if wave_number_squared == 0:
            if coefficient != 0:
                raise ValueError("pressure source has a nonzero mean")
            continue
        result[wavevector] = coefficient / wave_number_squared
    return result


def normalized_cosine_pairing(
    left: Wavevector,
    right: Wavevector,
) -> Fraction:
    """Return the normalized torus mean of two nonconstant cosine modes."""
    left = canonical_wavevector(left)
    right = canonical_wavevector(right)
    if left == (0, 0) or right == (0, 0):
        raise ValueError("this helper is for nonconstant modes")
    return Fraction(1, 2) if left == right else Fraction(0)


def critical_pressure_work_cubic_coefficient() -> Fraction:
    """Return the leading critical pressure-work coefficient.

    For ``V_e=e_1+e w`` the pressure is ``e^2 p`` and

    ``V_e dot grad |V_e| = e partial_x w_1 + O(e^2)``.

    Here ``partial_x w_1=cos(x+y)``, so the normalized leading coefficient
    is the pairing of ``p`` with that mode.
    """
    target = (1, 1)
    return pressure_modes().get(target, Fraction(0)) * (
        normalized_cosine_pairing(target, target)
    )


def report() -> str:
    return "\n".join(
        [
            "renormalised scale-hull balance ledger",
            (
                "L3 similarity drift coefficient: "
                f"{similarity_drift_coefficient(Fraction(3))}"
            ),
            (
                "L2 similarity drift coefficient: "
                f"{similarity_drift_coefficient(Fraction(2))}"
            ),
            (
                "L4 similarity drift coefficient: "
                f"{similarity_drift_coefficient(Fraction(4))}"
            ),
            (
                "gradient p=2+delta packet power: "
                f"{higher_integrability_packet_power(Fraction(1, 10))}"
            ),
            (
                "critical higher-integrability threshold delta: "
                f"{Fraction(1, 2)}"
            ),
            f"pressure Poisson modes: {pressure_modes()}",
            (
                "critical pressure-work cubic coefficient: "
                f"{critical_pressure_work_cubic_coefficient()}"
            ),
        ]
    )


if __name__ == "__main__":
    print(report())
